### ISSUE TITLE
podman build fails on step 6: Could not find a Mix.Project

### ISSUE THREAD

**Issue by proJM-Coding** [progval/matrix2051#83]
Hello, coming from issue #26 I mentioned that I couldn't build the image when using podman (I haven't tried with docker but I don't expect a difference). I have followed the steps listed in the [INSTALL.md](https://github.com/progval/matrix2051/blob/main/INSTALL.md) under the heading `Running matrix2051 as a container`:

`git clone https://github.com/progval/matrix2051.git`

`cd matrix2051`

`podman build -t matrix2051 --file dist/Containerfile .`

This fails on set 6 `RUN mix deps.get` with the error:

```
** (Mix) Could not find a Mix.Project, please ensure you are running Mix in a directory with a mix.exs file
Error: building at STEP "RUN mix deps.get": while running runtime: exit status 1
```

Looking at the Containerfile I don't understand why the `mix.exs` is not being picked up (Edit: I think when it is copying is will copy only the `dist` folder but this is just a guess. I have done nothing to look into it) so I hope someone can help me. Just in case I made an error, I did write down the error rather than copy since it was on a laptop without a functioning browser.

**Comment by progval** [comment]
If you add `RUN ls .` in the containerfile, does it show mix.exs?

**Comment by proJM-Coding** [comment]
Looks like the edit is correct. Only the `Containerfile` and `systemd` folder show when running `ls .`

Should the copy command be `COPY ../ /app` instead?

**Comment by proJM-Coding** [comment]
Moving the `Containerfile` into the root of the repo fixes this issue, I'm just waiting for it to finish compiling so I can confirm no other issues.

**Comment by proJM-Coding** [comment]
Hello! Coming back to this issue the real problem is not really with the `Containerfile` but just that the docs don't state you need to copy it to the root of the project folder. As I said before there is an active pr which add instructions for docker but also says that you need to copy the file. I'll make a better pr which will fix this issue soon

**Comment by progval** [comment]
I fixed the `Containerfile`: 0a3989a2e4126227aef38e10baa490b9064e83aa

**Comment by proJM-Coding** [comment]
Doesn't fix the issue like I thought it would. I don't really understand why and how the `Containerfile` works but it is still copying the `dist` folder

**Comment by proJM-Coding** [comment]
I don't see it as "fixing the code" but I'll have a look into how the `COPY` works for the `Containerfile`

**Comment by progval** [comment]
and actually it works for me after my fix:

```
tmp@magnesium:~/matrix2051$ podman build -t matrix2051 --file dist/Containerfile .
STEP 1/8: FROM docker.io/alpine:3.19
STEP 2/8: ENV MIX_ENV=prod
--> Using cache df460095fc6594fb445b22ae047ce80b8d5141433bc654a4868e81a65dd322e6
--> df460095fc6
STEP 3/8: RUN apk add --update --no-cache elixir
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
(1/7) Installing libgcc (13.2.1_git20231014-r0)
(2/7) Installing ncurses-terminfo-base (6.4_p20231125-r0)
(3/7) Installing libncursesw (6.4_p20231125-r0)
(4/7) Installing libstdc++ (13.2.1_git20231014-r0)
(5/7) Installing erlang (26.2.1-r0)
(6/7) Installing erlang-dev (26.2.1-r0)
(7/7) Installing elixir (1.15.7-r2)
Executing busybox-1.36.1-r19.trigger
OK: 91 MiB in 22 packages
--> a216d24a5af
STEP 4/8: WORKDIR /app
--> b081a610779
STEP 5/8: COPY ../ /app
--> aad741f8417
STEP 6/8: RUN mix deps.get
* creating /root/.mix/archives/hex-2.2.1
Resolving Hex dependencies...
Resolution completed in 0.034s
New:
  certifi 2.15.0
  hackney 1.24.1
  httpoison 1.8.2
  idna 6.1.1
  jason 1.4.4
  metrics 1.0.1
  mimerl 1.4.0
  mochiweb 3.2.2
  mox 1.0.2
  parse_trans 3.4.1
  ssl_verify_fun 1.1.7
  unicode_util_compat 0.7.1
* Getting mochiweb (Hex package)
* creating /root/.mix/elixir/1-15/rebar3
* Getting jason (Hex package)
* Getting httpoison (Hex package)
* Getting mox (Hex package)
* Getting hackney (Hex package)
* Getting certifi (Hex package)
* Getting idna (Hex package)
* Getting metrics (Hex package)
* Getting mimerl (Hex package)
* Getting parse_trans (Hex package)
* Getting ssl_verify_fun (Hex package)
* Getting unicode_util_compat (Hex package)
--> 413c83cf473
STEP 7/8: RUN mix release
===> Analyzing applications...
===> Compiling unicode_util_compat
===> Analyzing applications...
===> Compiling idna
==> jason
Compiling 10 files (.ex)
Generated jason app
===> Analyzing applications...
===> Compiling mimerl
==> ssl_verify_fun
Compiling 7 files (.erl)
Generated ssl_verify_fun app
===> Analyzing applications...
===> Compiling certifi
===> Analyzing applications...
===> Compiling parse_trans
===> Analyzing applications...
===> Compiling metrics
===> Analyzing applications...
===> Compiling hackney
==> httpoison
Compiling 3 files (.ex)
Generated httpoison app
===> Analyzing applications...
===> Compiling mochiweb
==> matrix2051
Compiling 26 files (.ex)
warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
  lib/application.ex:31: M51.Application.start/2

warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
  lib/matrix_client/client.ex:528: M51.MatrixClient.Client.get_base_url/2

warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
  lib/matrix_client/client.ex:539: M51.MatrixClient.Client.get_base_url/2

warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
  lib/matrix_client/sender.ex:86: M51.MatrixClient.Sender.loop_send/6

warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
  lib/matrix_client/poller.ex:91: M51.MatrixClient.Poller.poll_one/5

warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
  lib/matrix_client/sender.ex:73: M51.MatrixClient.Sender.loop_send/6

Generated matrix2051 app
* assembling matrix2051-0.1.0 on MIX_ENV=prod
* skipping runtime configuration (config/runtime.exs not found)
* skipping elixir.bat for windows (bin/elixir.bat not found in the Elixir installation)
* skipping iex.bat for windows (bin/iex.bat not found in the Elixir installation)

Release created at _build/prod/rel/matrix2051

    # To start your system
    _build/prod/rel/matrix2051/bin/matrix2051 start

Once the release is running:

    # To connect to it remotely
    _build/prod/rel/matrix2051/bin/matrix2051 remote

    # To stop it gracefully (you may also send SIGINT/SIGTERM)
    _build/prod/rel/matrix2051/bin/matrix2051 stop

To list all commands:

    _build/prod/rel/matrix2051/bin/matrix2051

--> fc966a3ae1d
STEP 8/8: CMD _build/prod/rel/matrix2051/bin/matrix2051 start
COMMIT matrix2051
--> dadd5686913
Successfully tagged localhost/matrix2051:latest
dadd5686913d5c0f5c3ae5cae175e2b06e99c028848b96b3a4f060a283b30dab
```

**Comment by ghost** [comment]
Nope, fresh `git clone` of your repo. I'm guessing something to do with cache but podman doesn't have the line ` --> Using cache` for that step. I'm going to test on a fresh system, I'll try to get back to you tomorrow. Thanks for being so responsive.

Edit: Building an image with docker now, no issues.
